using M2.Core;
using M2.Network;
using M2.Player;
using M2.UI;
using Unity.Netcode;
using Unity.Netcode.Transports.UTP;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.InputSystem.UI;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

namespace M2.Editor
{
    // Builds Assets/Scenes/NetworkBootstrap.unity — Milestone 1's minimal Host/Join scene (no
    // Relay/Lobby yet, direct UnityTransport connection only; see CLAUDE.md's Netcode section).
    // Same "persisted asset generated by an -executeMethod-callable Editor script" pattern as
    // TestTrackBuilder.BuildAndSavePersistedScene — re-run this (or BuildCheck.
    // BuildNetworkBootstrapScene in batch mode) any time this file changes to regenerate it.
    public static class NetworkBootstrapSceneBuilder
    {
        const string ScenePath = "Assets/Scenes/NetworkBootstrap.unity";
        const string VehiclePrefabPath = "Assets/Prefabs/Player/NetworkVehicle.prefab";

        [MenuItem("M2/Build Persisted Scene/Network Bootstrap (Milestone 1)")]
        public static void BuildAndSaveScene()
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            GameObject root = new GameObject("NetworkBootstrap");

            CreateGround(root.transform);
            CreateCamera(root.transform);
            NetworkBootstrapUI bootstrapUi = CreateNetworkManagerAndUi(root.transform);

            if (!AssetDatabase.IsValidFolder("Assets/Scenes"))
            {
                AssetDatabase.CreateFolder("Assets", "Scenes");
            }
            EditorSceneManager.SaveScene(scene, ScenePath);

            Debug.Log($"M2_NETWORK_BOOTSTRAP_SCENE_BUILT: {ScenePath} (bootstrapUi null? {bootstrapUi == null})");
        }

        static void CreateGround(Transform parent)
        {
            GameObject ground = GameObject.CreatePrimitive(PrimitiveType.Plane);
            ground.name = "Ground";
            ground.transform.SetParent(parent);
            ground.transform.localScale = new Vector3(6f, 1f, 6f);
            // Same lime green as the race tracks' off-track ground (19차 palette) — purely for
            // visual orientation while testing, no gameplay meaning here.
            RendererColorUtil.ApplyColor(ground.GetComponent<Renderer>(), new Color(0.714f, 0.953f, 0.420f));
        }

        static void CreateCamera(Transform parent)
        {
            GameObject cameraObject = new GameObject("Main Camera", typeof(Camera));
            cameraObject.tag = "MainCamera";
            cameraObject.transform.SetParent(parent);
            cameraObject.transform.position = new Vector3(0f, 6f, -8f);
            cameraObject.transform.rotation = Quaternion.Euler(30f, 0f, 0f);
            // target intentionally left unset — NetworkVehicleSync.OnNetworkSpawn retargets
            // this to the locally-owned vehicle once a player actually spawns.
            cameraObject.AddComponent<VehicleCameraFollow>();
        }

        static NetworkBootstrapUI CreateNetworkManagerAndUi(Transform parent)
        {
            GameObject vehiclePrefab = AssetDatabase.LoadAssetAtPath<GameObject>(VehiclePrefabPath);
            if (vehiclePrefab == null)
            {
                Debug.LogWarning($"M2: NetworkVehicle prefab not found at {VehiclePrefabPath} — run " +
                    "M2/Build Network Prefabs first. NetworkManager.PlayerPrefab left unset.");
            }

            NetworkManager networkManager = CreateNetworkManager(vehiclePrefab);
            return AttachHostJoinUi(parent, networkManager);
        }

        // Creates the root NetworkManager GameObject (UnityTransport + a scene-management-off
        // NetworkConfig, player prefab wired). Shared with NetworkRaceSceneBuilder so both
        // networked scenes create the manager identically. `vehiclePrefab` may be null (a
        // warning is logged by the caller) — PlayerPrefab just stays unset.
        internal static NetworkManager CreateNetworkManager(GameObject vehiclePrefab)
        {
            // NetworkManager must be a scene ROOT GameObject (no parent) — it calls
            // DontDestroyOnLoad on itself, which Unity only allows for root objects. Nesting it
            // under another root (as an earlier version of this did) triggers NGO's own
            // "NetworkManager is nested under [X]" validation error the moment you enter Play
            // mode (playtester feedback: "NetworkManager is nested under NetworkBootstrap.이라는데?").
            GameObject nmObject = new GameObject("NetworkManager");

            NetworkManager networkManager = nmObject.AddComponent<NetworkManager>();
            UnityTransport transport = nmObject.AddComponent<UnityTransport>();
            // NetworkManager.NetworkConfig has no field initializer in NGO's source
            // (`public NetworkConfig NetworkConfig;`) — the Inspector's normal "add component"
            // flow populates it with a default instance via Unity's serialization system, but
            // that never happens for a component added purely through an editor script like
            // this one, leaving it null (confirmed directly via a NullReferenceException on the
            // next line without this).
            networkManager.NetworkConfig = new NetworkConfig();
            networkManager.NetworkConfig.NetworkTransport = transport;

            // NGO's scene management (on by default) requires every scene a connected client
            // needs to synchronize into be registered in File > Build Settings > Scenes In
            // Build — this project has never added any scene there, which produced the runtime
            // warning "The current scene was not found in the scenes in build..." and left
            // ownership-dependent state (e.g. NetworkVehicleSync.OnNetworkSpawn's isKinematic
            // assignment) unreliable for a client joining after the host, since NGO's
            // scene-sync handshake never properly completed. Both networked scenes so far have a
            // single static scene each side loads independently (no NGO scene transitions), so
            // scene management isn't needed yet — turning it off sidesteps the whole requirement
            // until a later milestone actually needs multi-scene sync.
            networkManager.NetworkConfig.EnableSceneManagement = false;

            if (vehiclePrefab != null)
            {
                networkManager.NetworkConfig.PlayerPrefab = vehiclePrefab;
            }

            return networkManager;
        }

        // Adds the Relay room-code UI (buttons + code field + status text + EventSystem) to an existing
        // NetworkManager. The NetworkBootstrapUI component goes on the NetworkManager object
        // itself; the canvas/EventSystem go under `uiParent`. Shared with NetworkRaceSceneBuilder.
        internal static NetworkBootstrapUI AttachHostJoinUi(Transform uiParent, NetworkManager networkManager)
        {
            GameObject nmObject = networkManager.gameObject;
            NetworkBootstrapUI bootstrapUi = nmObject.AddComponent<NetworkBootstrapUI>();

            GameObject canvasObject = new GameObject("BootstrapCanvas");
            canvasObject.transform.SetParent(uiParent);
            Canvas canvas = canvasObject.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvasObject.AddComponent<CanvasScaler>();
            canvasObject.AddComponent<GraphicRaycaster>();

            // Same InputSystemUIInputModule requirement TestTrackBuilder.SetupHud already
            // documents — this project uses the New Input System exclusively, and a plain
            // EventSystem defaults to the legacy StandaloneInputModule, which never receives
            // clicks in this project.
            if (Object.FindFirstObjectByType<EventSystem>() == null)
            {
                GameObject eventSystemObject = new GameObject("EventSystem");
                eventSystemObject.transform.SetParent(uiParent);
                eventSystemObject.AddComponent<EventSystem>();
                var uiModule = eventSystemObject.AddComponent<InputSystemUIInputModule>();
                uiModule.AssignDefaultActions();
            }

            Button hostButton = SimpleUIFactory.CreateButton(canvasObject.transform, "HostButton", "방 만들기",
                new Vector2(-100f, 40f), new Vector2(180f, 60f));
            Button joinButton = SimpleUIFactory.CreateButton(canvasObject.transform, "JoinButton", "방 참가",
                new Vector2(100f, 40f), new Vector2(180f, 60f));
            InputField joinCodeInputField = CreateJoinCodeInputField(canvasObject.transform);
            Text statusText = SimpleUIFactory.CreateCornerText(canvasObject.transform, "StatusText",
                new Vector2(0.5f, 0f), new Vector2(0f, 20f), TextAnchor.LowerCenter);
            statusText.color = Color.white;

            bootstrapUi.hostButton = hostButton;
            bootstrapUi.joinButton = joinButton;
            bootstrapUi.joinCodeInputField = joinCodeInputField;
            bootstrapUi.statusText = statusText;

            return bootstrapUi;
        }

        // Unity's legacy InputField needs an Image background plus a child Text (the actual
        // typed value) — no shared factory for this yet since it's the first InputField this
        // project has needed (SimpleUIFactory only had Button/Text/Panel builders so far).
        static InputField CreateJoinCodeInputField(Transform parent)
        {
            GameObject fieldObject = new GameObject("JoinCodeInputField");
            fieldObject.transform.SetParent(parent, false);

            RectTransform rect = fieldObject.AddComponent<RectTransform>();
            rect.anchorMin = new Vector2(0.5f, 0.5f);
            rect.anchorMax = new Vector2(0.5f, 0.5f);
            rect.pivot = new Vector2(0.5f, 0.5f);
            rect.anchoredPosition = new Vector2(0f, -60f);
            rect.sizeDelta = new Vector2(260f, 50f);

            Image bg = fieldObject.AddComponent<Image>();
            bg.color = new Color(1f, 1f, 1f, 0.9f);

            InputField inputField = fieldObject.AddComponent<InputField>();

            GameObject textObject = new GameObject("Text");
            textObject.transform.SetParent(fieldObject.transform, false);
            Text text = textObject.AddComponent<Text>();
            text.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            text.fontSize = 24;
            text.color = Color.black;
            text.alignment = TextAnchor.MiddleCenter;
            RectTransform textRect = textObject.GetComponent<RectTransform>();
            textRect.anchorMin = Vector2.zero;
            textRect.anchorMax = Vector2.one;
            textRect.offsetMin = new Vector2(10f, 5f);
            textRect.offsetMax = new Vector2(-10f, -5f);

            GameObject placeholderObject = new GameObject("Placeholder");
            placeholderObject.transform.SetParent(fieldObject.transform, false);
            Text placeholder = placeholderObject.AddComponent<Text>();
            placeholder.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
            placeholder.fontSize = 24;
            placeholder.fontStyle = FontStyle.Italic;
            placeholder.color = new Color(0f, 0f, 0f, 0.4f);
            placeholder.alignment = TextAnchor.MiddleCenter;
            placeholder.text = "방 코드";
            RectTransform placeholderRect = placeholderObject.GetComponent<RectTransform>();
            placeholderRect.anchorMin = Vector2.zero;
            placeholderRect.anchorMax = Vector2.one;
            placeholderRect.offsetMin = new Vector2(10f, 5f);
            placeholderRect.offsetMax = new Vector2(-10f, -5f);

            inputField.textComponent = text;
            inputField.placeholder = placeholder;
            inputField.characterLimit = 12;

            return inputField;
        }
    }
}
