using M2.Core;
using M2.Network;
using M2.Player;
using M2.Stage;
using M2.UI;
using Unity.Netcode;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

namespace M2.Editor
{
    // Builds Assets/Scenes/NetworkRace.unity — Milestone 2a's networked race scene: a real
    // hand-authored track (reusing TestTrackBuilder.BuildTrackEnvironment, so it's the exact
    // same Bikini City layout the local scene uses) driven under Netcode with server-authoritative
    // race state (see NetworkRaceManager). Direct UnityTransport host/join, no Relay/Lobby yet.
    //
    // Same "persisted asset generated by an -executeMethod-callable Editor script" pattern as the
    // other scene builders — re-run this (or BuildCheck.BuildNetworkRaceScene in batch mode) any
    // time this file, the track, or the networked components change.
    public static class NetworkRaceSceneBuilder
    {
        const string ScenePath = "Assets/Scenes/NetworkRace.unity";
        const string VehiclePrefabPath = "Assets/Prefabs/Player/NetworkVehicle.prefab";
        const string RaceManagerPrefabPath = "Assets/Prefabs/Network/NetworkRaceManager.prefab";

        // Milestone 2a builds the online race on Bikini City only; other stages come later.
        const StageType Stage = StageType.BikiniCity;

        [MenuItem("M2/Build Persisted Scene/Network Race (Milestone 2a)")]
        public static void BuildAndSaveScene()
        {
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            GameObject root = new GameObject("NetworkRace");
            TrackGeometry geo = TestTrackBuilder.BuildTrackEnvironment(root.transform, Stage);

            CreateGameManager(root.transform);
            CreateStartGrid(root.transform, geo);
            NetworkManager networkManager = CreateNetworking(root.transform);
            CreateCamera(root.transform);
            CreateRaceHud(root.transform);

            if (!AssetDatabase.IsValidFolder("Assets/Scenes"))
            {
                AssetDatabase.CreateFolder("Assets", "Scenes");
            }
            EditorSceneManager.SaveScene(scene, ScenePath);

            Debug.Log($"M2_NETWORK_RACE_SCENE_BUILT: {ScenePath} (networkManager null? {networkManager == null})");
        }

        static void CreateGameManager(Transform parent)
        {
            GameObject gmObject = new GameObject("GameManager");
            gmObject.transform.SetParent(parent);
            GameManager gm = gmObject.AddComponent<GameManager>();
            // Networked: the host's NetworkRaceManager starts the flow once both players spawn,
            // not immediately at scene load, and a client's GameManager stays idle entirely.
            gm.autoStartOnStart = false;
            // Use the fixed briefing timer (not the local test track's manual "시작" button) —
            // the host auto-starts the whole flow when the grid fills, so there's no button to
            // press. The 4s briefing gives the just-connected client a moment before countdown.
            gm.waitForManualStart = false;
        }

        // Two staggered grid slots just behind the start/finish line (theta=0), matching the
        // local vehicle's spawn convention (PointAt(0) pulled back along the tangent). Cars read
        // this on spawn via NetworkVehicleSync -> RaceStartGrid.
        static void CreateStartGrid(Transform parent, TrackGeometry geo)
        {
            Vector3 lineCenter = geo.PointAt(0f);
            Vector3 tangent = geo.TangentAt(0f);
            Vector3 normal = geo.NormalAt(0f);

            Vector3 gridBase = lineCenter - tangent * 3f + Vector3.up * 0.5f;
            float lateral = TestTrackBuilder.CurrentTrackWidth * 0.22f;

            GameObject gridObject = new GameObject("RaceStartGrid");
            gridObject.transform.SetParent(parent);
            RaceStartGrid grid = gridObject.AddComponent<RaceStartGrid>();
            grid.slot0Position = gridBase + normal * lateral;
            grid.slot1Position = gridBase - normal * lateral;
            grid.facing = Quaternion.LookRotation(tangent, Vector3.up);
        }

        static NetworkManager CreateNetworking(Transform root)
        {
            GameObject vehiclePrefab = AssetDatabase.LoadAssetAtPath<GameObject>(VehiclePrefabPath);
            if (vehiclePrefab == null)
            {
                Debug.LogWarning($"M2: NetworkVehicle prefab not found at {VehiclePrefabPath} — run " +
                    "M2/Build Network Prefabs first. NetworkManager.PlayerPrefab left unset.");
            }

            NetworkManager networkManager = NetworkBootstrapSceneBuilder.CreateNetworkManager(vehiclePrefab);

            GameObject raceManagerPrefab = AssetDatabase.LoadAssetAtPath<GameObject>(RaceManagerPrefabPath);
            if (raceManagerPrefab == null)
            {
                Debug.LogWarning($"M2: NetworkRaceManager prefab not found at {RaceManagerPrefabPath} — run " +
                    "M2/Build Network Race Manager Prefab first. Race manager won't spawn.");
            }
            // NOTE: the race-manager prefab is registered at RUNTIME by NetworkRaceBootstrap
            // (AddNetworkPrefab), not here — NetworkPrefabs.m_Prefabs is [NonSerialized], so a
            // NetworkConfig.Prefabs.Add() made at scene-authoring time would be lost on save.

            NetworkBootstrapSceneBuilder.AttachHostJoinUi(root, networkManager);

            // Lives on the NetworkManager object (which DontDestroyOnLoads itself) and spawns the
            // race manager once the host's server starts. It also registers the prefab above.
            NetworkRaceBootstrap bootstrap = networkManager.gameObject.AddComponent<NetworkRaceBootstrap>();
            bootstrap.raceManagerPrefab = raceManagerPrefab;

            return networkManager;
        }

        static void CreateCamera(Transform parent)
        {
            GameObject cameraObject = new GameObject("Main Camera", typeof(Camera));
            cameraObject.tag = "MainCamera";
            cameraObject.transform.SetParent(parent);
            cameraObject.transform.position = new Vector3(0f, 10f, -14f);
            cameraObject.transform.rotation = Quaternion.Euler(35f, 0f, 0f);
            // target left unset — NetworkVehicleSync.OnNetworkSpawn retargets this to the locally
            // owned vehicle once a player spawns (same as the bootstrap scene's camera).
            cameraObject.AddComponent<VehicleCameraFollow>();
        }

        static void CreateRaceHud(Transform parent)
        {
            GameObject canvasObject = new GameObject("RaceHUDCanvas");
            canvasObject.transform.SetParent(parent);
            Canvas canvas = canvasObject.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvasObject.AddComponent<CanvasScaler>();
            canvasObject.AddComponent<GraphicRaycaster>();

            // Top-left info line (state / time / laps).
            Text infoLabel = SimpleUIFactory.CreateCornerText(canvasObject.transform, "RaceInfoLabel",
                new Vector2(0f, 1f), new Vector2(20f, -20f), TextAnchor.UpperLeft);
            infoLabel.color = Color.white;
            infoLabel.rectTransform.sizeDelta = new Vector2(320f, 200f);

            // Big center banner (countdown / GO! / result).
            Text bannerLabel = SimpleUIFactory.CreateCenteredText(canvasObject.transform, "RaceBannerLabel",
                72, Color.yellow);
            bannerLabel.fontStyle = FontStyle.Bold;

            NetworkRaceHUD hud = canvasObject.AddComponent<NetworkRaceHUD>();
            hud.bannerLabel = bannerLabel;
            hud.infoLabel = infoLabel;
        }
    }
}
